module.exports = {
    statusFailure: false,
    statusSuccess: true,
    serverError: 'We are unable to process your request, Please try later',
    userEmailExist: 'User email already exist',
    userPhoneExist: 'User phone already exist',
    userNotExist: 'User not exist',
    getData: 'Data loaded successfully.',
    noDataFound: 'No result found',
    dataCreated: 'Data inserted successfully.',
    dataNotCreated: 'Data not inserted.',
    dataUpdated: 'Data updated successfully.',
    dataNotUpdated: 'Data not updated', 
    dataDeleted: 'Data deleted successfully',
    dataNotDeleted: 'Data not deleted.',  
    AccontCreated:'Account Created, OTP has been sent to registered email ID',
    loginSuccess:'Logged in successfully',
    loginFailed:'Please enter correct password',
    accountBlocked : 'Your account has been blocked by admin',
    otpSent : 'OTP has been sent to registered email ID. Valid for 5 minutes',
    invalidOTP : "Invalid OTP",
    otpVerified : "OTP verified",
    otpExpired : "OTP has been expired",    
    unauthorised : "Unauthorised Access",
    invalidToken : "Invalid Access Token",
}